import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartProvider from "./components/Providers";
import Navbar from "./components/navbar";
import ShoppingCartModal from "./components/ShoppingCartModal";
import Footer from "./components/footer";
import ScrollReveal from "./components/ScrollReveal";
import {
  ClerkProvider,
 
} from '@clerk/nextjs'
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  
}: {
  children: React.ReactNode;
  
}) {
 
  return (
   
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
      
        
     
        <ScrollReveal>
       
        <CartProvider>
          <TopBar/>
          <Navbar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
        <Footer/>
       </ScrollReveal>
       </ClerkProvider>
      </body>
      
    </html>
   
  );
}


